### ISSUE TITLE
Generating Keys

### ISSUE THREAD

**Issue by blissville** [jkrauze/mceliece#3]
How do I generate the PUB_KEY_FILE and PRIV_KEY_FILE?

**Comment by jkrauze** [comment]
Please see an example in a similar project with almost the same user interface [here](https://github.com/jkrauze/ntru).

**Comment by blissville** [comment]
> Please see an example in a similar project with almost the same user interface [here](https://github.com/jkrauze/ntru).

thank you. i have seen it

**Comment by jkrauze** [comment]
I hope that helped.
